In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
def get_jobs_list(soup_GD):
    try:
        jobs_list = soup_GD.find_all('li', class_='JobsList_jobListItem__JBBUV')
    except AttributeError:
        jobs_list = []
        
    return jobs_list

In [3]:
def get_comp_name(soup_GD, job):
    try:
        company_name = job.find('div', class_='css-8wag7x').text
        company_name = ''.join(i for i in company_name if ((i.isalpha()) | (i == ' ')))
        company_name = company_name.strip()
    except AttributeError:
        company_name = ''
        
    return company_name

In [4]:
def get_job_location(soup_GD, job):
    try:
        job_location = job.find('div', class_='location mt-xxsm').text
    except AttributeError:
        job_location = ''
        
    return job_location

In [5]:
def get_job_salary(soup_GD, job):
    try:
        estimated_salary = job.find('div', class_='salary-estimate').text.split('\xa0')[0]
    except AttributeError:
        estimated_salary = ''
        
    return estimated_salary

In [6]:
URL_GD = 'https://www.glassdoor.co.in/Job/india-data-engineer-jobs-SRCH_IL.0,5_IN115_KO6,19.htm'
Hearders = ({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.5'})

webpage = requests.get(URL_GD, headers=Hearders)
company_name = []
job_location = []
estimated_salary = []
soup_GD = BeautifulSoup(webpage.content, 'html.parser')
jobs_list = get_jobs_list(soup_GD)

for job in jobs_list:
    company_name.append(get_comp_name(soup_GD, job))
    job_location.append(get_job_location(soup_GD, job))
    estimated_salary.append(get_job_salary(soup_GD, job))
    
print(company_name)
print(len(company_name))
print(job_location)
print(estimated_salary)
info_dic = {'company_name': company_name, 'job_location': job_location, 'estimated_salary': estimated_salary}
print(info_dic)

['', 'True Tech Professionals Private Limited', 'Electronic Arts', 'Foraysoft', 'Fractal Analytics', 'Calix', 'ThinkSys', 'Valueonshore Advisors', '', 'KPMG', '', 'Deutsche Bank', '', 'Mimecast', 'Codvoai', 'Careator Technologies Private Limited', 'MercedesBenz Research and Development India Private Limited', 'Grid Infocom', '', '']
20
['Gurgaon', 'Gurgaon', 'Hyderābād', 'Gurgaon', 'Gurgaon', 'Bengaluru', 'Noida', 'Gurgaon', 'Bengaluru', 'Gurgaon', 'New Delhi', 'Pune', 'Bengaluru', 'Bengaluru', 'Remote', 'Bengaluru', 'Bengaluru', 'Remote', 'Bengaluru', 'Cochin']
['₹22L - ₹30L', '₹10L - ₹40L', '₹9L - ₹10L', '₹6L - ₹8L', '₹8L - ₹10L', '₹7L - ₹10L', '₹5L - ₹6L', '₹5L - ₹8L', '₹15L - ₹25L', '₹6L', '₹50T - ₹90T', '₹2L', '₹28L', '₹4L - ₹6L', '₹5L - ₹18L', '₹4L - ₹16L', '₹6L - ₹7L', '₹3L', '₹20L - ₹23L', '₹5L - ₹9L']
{'company_name': ['', 'True Tech Professionals Private Limited', 'Electronic Arts', 'Foraysoft', 'Fractal Analytics', 'Calix', 'ThinkSys', 'Valueonshore Advisors', '', 'KPMG', '', 'Deutsche Bank', '', 'Mimecast', 'Codvoai', 'Careator Technologies Private Limited', 'MercedesBenz Research and Development India Private Limited', 'Grid Infocom', '', ''], 'job_location': ['Gurgaon', 'Gurgaon', 'Hyderābād', 'Gurgaon', 'Gurgaon', 'Bengaluru', 'Noida', 'Gurgaon', 'Bengaluru', 'Gurgaon', 'New Delhi', 'Pune', 'Bengaluru', 'Bengaluru', 'Remote', 'Bengaluru', 'Bengaluru', 'Remote', 'Bengaluru', 'Cochin'], 'estimated_salary': ['₹22L - ₹30L', '₹10L - ₹40L', '₹9L - ₹10L', '₹6L - ₹8L', '₹8L - ₹10L', '₹7L - ₹10L', '₹5L - ₹6L', '₹5L - ₹8L', '₹15L - ₹25L', '₹6L', '₹50T - ₹90T', '₹2L', '₹28L', '₹4L - ₹6L', '₹5L - ₹18L', '₹4L - ₹16L', '₹6L - ₹7L', '₹3L', '₹20L - ₹23L', '₹5L - ₹9L']}

In [7]:
df = pd.DataFrame.from_dict(info_dic)

In [8]:
df

,company_name,job_location,estimated_salary
0,,Gurgaon,₹22L - ₹30L
1,True Tech Professionals Private Limited,Gurgaon,₹10L - ₹40L
2,Electronic Arts,Hyderābād,₹9L - ₹10L
3,Foraysoft,Gurgaon,₹6L - ₹8L
4,Fractal Analytics,Gurgaon,₹8L - ₹10L
5,Calix,Bengaluru,₹7L - ₹10L
6,ThinkSys,Noida,₹5L - ₹6L
7,Valueonshore Advisors,Gurgaon,₹5L - ₹8L
8,,Bengaluru,₹15L - ₹25L
9,KPMG,Gurgaon,₹6L
10,,New Delhi,₹50T - ₹90T
11,Deutsche Bank,Pune,₹2L
12,,Bengaluru,₹28L
13,Mimecast,Bengaluru,₹4L - ₹6L
14,Codvoai,Remote,₹5L - ₹18L
15,Careator Technologies Private Limited,Bengaluru,₹4L - ₹16L
16,MercedesBenz Research and Development India Pr...,Bengaluru,₹6L - ₹7L
17,Grid Infocom,Remote,₹3L
18,,Bengaluru,₹20L - ₹23L
19,,Cochin,₹5L - ₹9L